inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Gemfile
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/AbcSize:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
