name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Set up node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: harmon758/postgresql-action@v1
        with:
        postgresql version: '9.6'
    - name: Build and test with Rake
      run: |
        ls -la
        echo $PATH
        which node
        node --version
        which npm
        npm install -g yarn
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:setup
        bundle exec rake
